sjk/urls.py
from django.contrib import admin
from django.urls import path
from app.views import *

urlpatterns = [
    path('admin/', admin.site.urls, name= 'admin'),
    path('', index, name= 'index'),
    path('login/', index_login,name= 'login'),
    path('logout/', index_logout, name='logout'),
    path('register/', register, name= 'register'),
    path('infomanage/',infomanage, name= 'infomanage' ),
    path('infochange/', infochange, name= 'infochange'),
    path('instore/', instore, name= 'instore'),
    path('outstore/', outstore, name= 'outstore'),
    path('getGoodInfo/',getGoodInfo,name='getGoodInfo'),
    path('getSupInfo/',getSupInfo,name='getSupInfo'),
]

app/forms.py
from django import forms
class UserForm(forms.Form):
    username = forms.CharField(label='账号:')
    password = forms.CharField(label='密码:', widget= forms.PasswordInput)


class UserInfoForm(forms.Form):
    username = forms.CharField(label='用户名:')
    # name = forms.CharField(label='姓名:')
    password = forms.CharField(label='密码:',widget= forms.PasswordInput)
    # job_num = forms.IntegerField(label='工号:')
    sex_choice = {('男', '男'), ('女', '女'), }
    job_choice = {('普通员工', '普通员工'), ('仓库主管','仓库主管'),('用户','用户')}
    sex = forms.ChoiceField(label='性别:', choices= sex_choice)
    job = forms.ChoiceField(label='职位:', choices= job_choice)


class InfoChange(forms.Form):
    password = forms.CharField(label='请输入新密码:',widget= forms.PasswordInput)
    password_again = forms.CharField(label='再次输入新密码:',widget= forms.PasswordInput)
    # sex_choice = {('male', '男'), ('female', '女'), }
    # job_choice = {('普通员工', '普通员工'), ('仓库主管','仓库主管'),('用户','用户')}
    # sex = forms.ChoiceField(label='性别:', choices= sex_choice)
    # job = forms.ChoiceField(label='职位:', choices= job_choice)

class StoreIn(forms.Form):
    goods_name = forms.CharField(label='11货物名称:')
    goodsID = forms.IntegerField(label='货物编号')
    sup_name = forms.CharField(label='供应商:')
    op_price = forms.FloatField(label='操作单价:')
    op_amount = forms.IntegerField(label='操作数量:')
    op_ps = forms.CharField(label='备注:')

class StoreOut(forms.Form):
    goods_name = forms.CharField(label='货物名称:')
    goodsID = forms.IntegerField(label='货物编号')
    sup_name = forms.CharField(label='供应商:')
    op_price = forms.FloatField(label='建议售价:')
    op_amount = forms.IntegerField(label='操作数量:')
    op_ps = forms.CharField(label='备注:')

app/templates/infochange.html
    <!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到小型自选商场管理系统</title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.all.js"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
</head>
{% if messages %}

    <script>
        $(function () {
            {% for msg in messages %}
                {#alert('{{ msg.message }}');#}
                layer.msg('{{ msg.message }}');
            {% endfor %}

        })
        // 标记是否有错误信息
    alt = true

    </script>
{% endif %}
<body class="layui-bg-gray">
    {% if messages %}
       <ul class=" ui red header messages" style="background-color: cornflowerblue; position: absolute;top: 60%;left: 42%;">
           {% for message in messages %}
           <P {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</P>
           {% endfor %}
       </ul>
    {% endif %}
   <div class="ui center segment"
                style=" min-height: 540px;
                opacity: 0.8;
                background-color: ghostwhite;
                width:315px !important;
                border:rgba(255, 0, 0, 0);
                position: absolute;
                left: 50%;
                top:50%;
                transform: translate(-50%,-50%);">
       <div class="ui center content login">
           <div class="ui header">
               <h2 class="ui red">密码更改</h2>
               <form action="/infochange/" method="post" style="position: absolute;top: 10%;left: 5%;">
                   {% csrf_token %}
                   <div class="field">
                       <div class="ui left icon input">
                            {{ form.as_p }}
                       </div>
                   </div>
                   <button class="ui center red submit button" style="position: absolute;top: 120%;left: 10%;">确认更改</button>
                   <a href="../infomanage/" class="ui center red button" style="position: absolute;top: 120%;left: 50%;">返回</a>
               </form>
           </div>
       </div>
   </div>





</body>
</html>

app/templates/instore.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="{% static 'css/semantic.css' %}">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.all.js"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>

<script>
    alt = false
</script>

{% if messages %}

    <script>
        $(function () {
            {% for msg in messages %}
                {#alert('{{ msg.message }}');#}
                layer.msg('{{ msg.message }}');
            {% endfor %}

        })
        // 标记是否有错误信息
    alt = true

    </script>
{% endif %}
<body class="layui-bg-gray">
    <meta charset="UTF-8">
    <title>入库</title>
    <div class="ui center segment"
                style=" min-height: 600px;
                opacity: 0.8;
                background-color: ghostwhite;
                width:500px !important;
                border:rgba(255, 0, 0, 0);
                position: absolute;
                left: 50%;
                top:50%;
                transform: translate(-50%,-50%);">
       <div>
           <div class="ui header">
               <h2 class="ui red">入库</h2>
               <form action="/instore/" method="post" style="position: absolute;top: 10%;left: 20%;">
                   {% csrf_token %}
                   <div class="field">
                       <div class="ui left icon input" style="width:120%;height:10%;">
                            {{ form.as_p }}
                       </div>
                   </div>
                   <button class="ui center blue submit button" style="position: absolute;top: 105%;left: 25%;">确定</button>
                   <a href="../infomanage/" class="ui center blue button" style="position: absolute;top: 105%;left: 45%;">返回</a>
               </form>
               {% if messages %}
                   <ul class=" ui black header messages" style="background-color: cornflowerblue; position: absolute;top: 100%;left: 35%;">
                    {% for message in messages %}
                        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                    </ul>
               {% endif %}
           </div>
       </div>
   </div>
<script type="text/javascript">
    goods = []
    sups=[]
    $.get("/getGoodInfo",function (ret) {
        console.log(ret)
        goods = ret
    })

    $.get("/getSupInfo",function (ret) {
        console.log(ret)
        sups = ret
    })


    $('#id_goodsID').bind('input propertychange', function () {
        id = $('#id_goodsID').val()
        if (id < 1){
            alert('id不能小于1')
            $('#id_goodsID').val('')
            return
        }
        {#good = goods[id - 1]#}
        good = getByid(goods, 'goodsID', id)
        loadGoodInfo(good)
    });

    function loadGoodInfo(good) {
        console.log(good)
        $('#id_goods_name').val(good['goods_name'])
        $('#id_op_price').val(good['goods_price'])
        sup_id = good['goods_sup']
        console.log(sup_id)
        //console.log(sups[sup_id - 1])
        sup_name = getByid(sups, 'id', sup_id)
        console.log(sup_name)
        $('#id_sup_name').val(sup_name['sup_name'])
    }

    function getByid(list, tag, val) {
        for (item of list) {
            console.log(item, val,item[tag] )
            if (item[tag] == val){
                return item
            }
        }
        console.log("没找到")

    }

</script>
</body>
</html>

app/templates/login.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到小型自选商场管理系统</title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
    <script src="/static/layui/layui.all.js"></script>

</head>


{#<div id="div_message" >#}
{#    {% if messages %}#}
{#       <ul class=" ui red header messages" style="background-color: ghostwhite; position: absolute;top: 65%;left: 42%;">#}
{#       <ul>#}
{#           {% for message in messages %}#}
{#           <P {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</P>#}
{#           {% endfor %}#}
{#       </ul>#}
{#    {% endif %}#}
{#</div>#}
<body class="layui-bg-gray">
{% if messages %}

    <script>
        $(function () {
            {% for msg in messages %}
                {#alert('{{ msg.message }}');#}
                layer.msg('{{ msg.message }}');
            {% endfor %}

        })

    </script>
{% endif %}

<script type="text/javascript">
    ;!function () {
        var layer = layui.layer
            , form = layui.form
            , element = layui.element;

    }();
    //注意：导航 依赖 element 模块，否则无法进行功能性操作.



</script>


   <div class="ui center segment"
                style=" min-height: 300px;
                opacity: 0.8;
                background-color: ghostwhite;
                width:315px !important;
                border:rgba(255, 0, 0, 0);
                position: absolute;
                left: 50%;
                top:40%;
                transform: translate(-50%,-50%);">
       <div class="ui center content login">
           <div class="ui header">
               <h2 class="ui red">欢迎登录</h2>
               <form action="/login/" method="post" style="position: absolute;top: 18%;left: 5%;">
                   {% csrf_token %}
                   <div class="field">
                       <div class="ui left icon input">
                            {{ form.as_p }}
                       </div>
                   </div>
                   <a href="/register/" class="ui user icon" style="position: absolute;top: 105%;left: 70%;">注册</a>
                   <button class="ui center red submit button" style="position: absolute;top: 120%;left: 35%;">登录</button>
               </form>
           </div>
       </div>
   </div>


</body>
</html>

app/templates/outstore.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<link rel="stylesheet" href="{% static 'css/semantic.css' %}">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.all.js"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
<script>
    alt = false
</script>

{% if messages %}

    <script>
        $(function () {
            {% for msg in messages %}
                {#alert('{{ msg.message }}');#}
                layer.msg('{{ msg.message }}');
            {% endfor %}

        })
        // 标记是否有错误信息
    alt = true

    </script>
{% endif %}
<body class="layui-bg-gray">
    <meta charset="UTF-8">
    <title>出库</title>
    <div class="ui center segment"
                style=" min-height: 600px;
                opacity: 0.8;
                background-color: ghostwhite;
                width:500px !important;
                border:rgba(255, 0, 0, 0);
                position: absolute;
                left: 50%;
                top:50%;
                transform: translate(-50%,-50%);">
       <div>
           <div class="ui header">
               <h2 class="ui red">出库</h2>
               <form action="/outstore/" method="post" style="position: absolute;top: 10%;left: 20%;">
                   {% csrf_token %}
                   <div class="field">
                       <div class="ui left icon input" style="width:120%;height:10%;">
                            {{ form.as_p }}
                       </div>
                   </div>
                   <button class="ui center blue submit button" style="position: absolute;top: 105%;left: 25%;">确定</button>
                   <a href="../infomanage/" class="ui center blue button" style="position: absolute;top: 105%;left: 45%;">返回</a>
               </form>
               {% if messages %}
                   <ul class=" ui black header messages" style="background-color: cornflowerblue; position: absolute;top: 100%;left: 35%;">
                    {% for message in messages %}
                        <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                    {% endfor %}
                    </ul>
               {% endif %}
           </div>
       </div>
   </div>
</body>
<script type="text/javascript">
    goods = []
    sups=[]
    $.get("/getGoodInfo",function (ret) {
        console.log(ret)
        goods = ret
    })

    $.get("/getSupInfo",function (ret) {
        console.log(ret)
        sups = ret
    })


    $('#id_goodsID').bind('input propertychange', function () {
        id = $('#id_goodsID').val()
        if (id < 1){
            alert('id不能小于1')
            $('#id_goodsID').val('')
            return
        }
        {#good = goods[id - 1]#}
        good = getByid(goods, 'goodsID', id)
        loadGoodInfo(good)
    });

    function loadGoodInfo(good) {
        console.log(good)
        $('#id_goods_name').val(good['goods_name'])
        $('#id_op_price').val(good['goods_price'])
        sup_id = good['goods_sup']
        console.log(sup_id)
        //console.log(sups[sup_id - 1])
        sup_name = getByid(sups, 'id', sup_id)
        console.log(sup_name)
        $('#id_sup_name').val(sup_name['sup_name'])
    }

    function getByid(list, tag, val) {
        for (item of list) {
            console.log(item, val,item[tag] )
            if (item[tag] == val){
                return item
            }
        }
        console.log("没找到")

    }

</script>
</html>

app/templates/register.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到小型自选商场管理系统</title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.all.js"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
</head>
{% if messages %}

    <script>
        $(function () {
            {% for msg in messages %}
                {#alert('{{ msg.message }}');#}
                layer.msg('{{ msg.message }}');
            {% endfor %}

        })
        // 标记是否有错误信息
    alt = true

    </script>
{% endif %}
<body class="layui-bg-gray">
{#    {% if messages %}#}
{#       <ul class=" ui red header messages" style="background-color: ghostwhite; position: absolute;top: 71%;left: 45%;">#}
{#           {% for message in messages %}#}
{#           <P {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</P>#}
{#           {% endfor %}#}
{#       </ul>#}
{#    {% endif %}#}
   <div class="ui center segment"
                style=" min-height: 500px;
                opacity: 0.8;
                background-color: ghostwhite;
                width:315px !important;
                border:rgba(255, 0, 0, 0);
                position: absolute;
                left: 50%;
                top:50%;
                transform: translate(-50%,-50%);">
       <div class="ui center content login">
           <div class="ui header">
               <h2 class="ui red">欢迎注册</h2>
               <form action="/register/" method="post" style="position: absolute;top: 10%;left: 5%;">
                   {% csrf_token %}
                   <div class="field">
                       <div class="ui left icon input">
                            {{ form.as_p }}
                       </div>
                   </div>
                   <a href="/login/" class="ui user icon" style="position: absolute;top: 105%;left: 70%;">已有账号</a>
                   <button class="ui center red submit button" style="position: absolute;top: 115%;left: 35%;">注册</button>
               </form>
           </div>
       </div>
   </div>

</body>
</html>

app/templates/userinfo.html
<!DOCTYPE html>
{% load static %}
<html lang="en" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>欢迎来到小型自选商场管理系统</title>
    <link rel="stylesheet" href="{% static 'css/semantic.css' %}" media="screen" title="no title" charset="utf-8">
    <link rel="stylesheet" href="/static/layui/css/layui.css">
    <script src="/static/layui/layui.all.js"></script>
    <script src="https://cdn.staticfile.org/jquery/1.10.2/jquery.min.js"></script>
</head>
<body class="layui-bg-gray" style="background: url({% static 'images/user_bg.jpg' %}); background-size: cover">
    <div class="ui contain">
                <!--菜单栏部分-->
        <div class="ui eight item menu" style="background-color: white;height: 80px;opacity: 0.7">

            <div class="item">
                <a href="?query=goods" methods="get" class="ui {{ goods_inver }} primary blue button">商品信息</a>
            </div>
            <div class="item">
                <a href="?query=sellout" methods="get" class="ui {{ sellout_inver }} primary blue button">消费记录</a>
            </div>
            <div class="item">
                <a href="/logout/" class="ui  primary red button">退出系统</a>
            </div>

        </div>
                <!--左侧个人基础信息segment-->
        <div class="ui segment" style=" min-height: 400px;
                    opacity: 0.5;
                    background-color: ghostwhite;
                    width: 220px !important;
                    border:rgba(255, 0, 0, 0);
                    position: absolute;
                    left: 10%;
                    top:45%;
                    transform: translate(-50%,-50%);">
            <div class="ui image">
                <i class="ui massive user icon"></i>
                <h3 class="ui center header">
                    用户名:&nbsp&nbsp&nbsp {{request.user.username}}
                </h3>
                <h3 class="ui center">
                    用户名:&nbsp&nbsp&nbsp<i class="man icon"></i>
                </h3>
{#                <h3 class="ui center">#}
{#                    职位:&nbsp&nbsp&nbsp{{request.user.userinfo.job}}#}
{#                </h3>#}
                <h3 class="ui center">
                    编号:&nbsp&nbsp&nbsp{{request.user.userinfo.job_num}}
                </h3>
                <br>
                <a href="/infochange/" class="ui center red button" >更改信息</a>
        </div>
    </div>

        <!--主要功能区部分，最大最麻烦 0.0-->
    <div class="ui right segment" style="background-color: ghostwhite; opacity: 0.7; width: 60%;margin-top: 2.5em;left: 30%">
        {% if  sell  %}
        购买成功！
    {% endif %}
        <!--供应商查询-->
        {% if name == 'supplier' %}
            <table class="ui red table">
            <thead>
                <tr>
                    <th>供应商编号</th>
                    <th>供应商名称</th>
                    <th>供应商电话</th>
              </tr>
            </thead>
            {% for sup in each_object %}
            <tbody>
                <tr>
                  <td>{{sup.supID}}</td>
                  <td>{{ sup.sup_name }}</td>
                  <td>{{ sup.sup_tel }}</td>
                </tr>
            </tbody>
            {% endfor %}
            </table>
        {% endif %}

        <!--商品查询查询-->
        {% if name == 'goods' %}
{#        <form class="ui" method="get">#}
{#                <tr>#}
{#                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#}
{#                    <th>货物名称or编号:</th>#}
{#                    <input  class="ui" type="text" name="goodsInfo" size="10" >#}
{#                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#}
{#                    <th>价格区间:</th>#}
{#                    <input  class="ui" type="text" name="goodsMAX" size="5" >----#}
{#                    <input  class="ui" type="text" name="goodsMIN" size="5" >#}
{#                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;#}
{#                    <button  class="ui red button" >筛选</button>#}
{#                </tr>#}
{#        </form>#}
            <table class="ui red table">
            <thead>
                <tr>
					<th>货物名称</th>
                    <th>货物编号</th>
                    <th>售价</th>
                    <th>折扣</th>
{#                    <th>总成本</th>#}
{#					<th>总营收</th>#}
                    <th>在售数量</th>
{#                    <th>最大库存量</th>#}
					<th>供应商名称</th>
                    <th>购买</th>
              </tr>
            </thead>
{#            add#}
            {% for good in each_object %}
            <tbody>
                <tr>
                <form method="get">
                  <td>{{ good.goods_name }}</td>
                  <td>{{ good.goodsID }}</td>
				  <td>{{ good.goods_sprice}}</td>
                  <td>{{ good.goods_discount}}</td>
                  <td>{{ good.good_amount}}</td>
{#                  <td>{{ good.goods_max}}</td>#}
                  <td>{{ good.goods_sup}}</td>
{#                <form action="/test.php" method="get">#}
                <td>
                <input type="number" name={{  good.goods_name }} min="1"  style="width:41px;">
                <input type="submit" >
                </td>
                </form>
                  {% if good.wave_goods.in_amount %}
                      {% if good.good_amount %}
                            {% if good.stock_goods.out_amount %}
                                <td>{{ good.good_amount|add:good.wave_goods.in_amount|add:good.stock_goods.out_amount }}</td>
                            {% else %}
                              <td>{{ good.good_amount|add:good.wave_goods.in_amount }}</td>
                            {% endif %}
                      {% else %}
                        <td>{{ good.good_amount|add:good.wave_goods.in_amount }}</td>
                      {% endif %}
                  {% else %}
                  {% endif %}

                </tr>
            </tbody>
            {% endfor %}
            </table>

            {% if messages %}
           <ul class=" ui red header messages" style="background-color: ghostwhite; position: absolute;top: 100%;left: 35%;">
               {% for message in messages %}
               <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
               {% endfor %}
           </ul>
            {% endif %}
        {% endif %}

           {% if name == 'sellout' %}
            <table class="ui red table">
            <thead>
                <tr>
					<th>商品名称</th>
                    <th>购买用户</th>
                    <th>购买数量</th>
					<th>购买时间</th>
              </tr>
            </thead>
            {% for good in each_object %}
            <tbody>
                <tr>
                  <td>{{ good.goods_name }}</td>
                  <td>{{ good.res_person }}</td>
                  <td>{{ good.out_amount }}</td>
                  <td>{{ good.out_date }}</td>
                </tr>
            </tbody>
            {% endfor %}
            {#  如何计算总营收 #}
            <tbody>
                <tr>
                    <td>总消费</td>
                    <td></td>
                    <td></td>
                    <td>￥{{  money}}</td>
                </tr>
            </tbody>
            </table>
            {% if messages %}
               <ul class=" ui red header messages" style="background-color: ghostwhite; position: absolute;top: 100%;left: 35%;">
                   {% for message in messages %}
                   <p {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</p>
                   {% endfor %}
               </ul>
            {% endif %}
        {% endif %}


        <div class="ui header">
            {% for pg in each_object.paginator.page_range %}
                {% if each_object.number == pg %}
                    <a  class="ui active red header" href="?query={{ name }}&page={{ pg }}">&nbsp;{{ pg }}</a>
                {% else %}
                    <a  class="ui header" href="?query={{ name }}&page={{ pg }}">&nbsp;{{ pg }}</a>
                {% endif %}
            {% endfor %}
        </div>
        </div>
        <div class="ui large buttons" style="position: absolute;top: 90%;left: 53%">
          {% if each_object.has_previous %}
            <a href="?query={{ name }}&page={{ each_object.previous_page_number }}" class="ui red button">上一页</a>
          {% else %}
            <a class="ui button">上一页</a>
          {% endif %}
          <div class=" ui or"></div>
          {% if each_object.has_next %}
            <a href="?query={{ name }}&page={{ each_object.next_page_number }}"  class="ui blue button active">下一页</a>
          {% else %}
             <a class="ui button">下一页</a>
          {% endif %}
        </div>
    </div>
</body>
</html>